package com.lendbiz.p2p.api.request.baovietEntity;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class ListBvgAddBaseVM {
    private String chuongTrinhBh = "";
    private long discount;
    private String gycbhId = "";
    private boolean hasExtracare;
    private boolean hasNguoithuhuong;
    private ImgGks imgGks;
    private String ketqua = "";
    private String ngoaitruChk = "";
    private long ngoaitruPhi;
    private String nguoidbhCmnd = "";
    private String nguoidbhDiachi = "";
    private String nguoidbhDienthoai = "";
    private String nguoidbhEmail = "";
    private String nguoidbhGioitinh = "";
    private String nguoidbhName = "";
    private String nguoidbhNgaysinh = "";
    private String nguoidbhQuanhe = "";
    private String nguoithCmnd = "";
    private String nguoithDiachi = "";
    private String nguoithDienthoai = "";
    private String nguoithEmail = "";
    private String nguoithName = "";
    private String nguoithNgaysinh = "";
    private String nguoithQuanhe = "";
    private String nhakhoaChk = "";
    private float nhakhoaPhi;
    private long percentId;
    private String policyParent = "";
    private long qlChinhPhi;
    private String showGiamDinh = "";
    private String smcnChk = "";
    private float smcnPhi;
    private String smcnSotienbh = "";
    private String smcnSotienbhTemp = "";
    private long tanggiamPhi;
    private String tanggiamPhiNoidung = "";
    private String riskAssessmentStatus = "";
    private String isShowPersonList = "";
    private String thaisanChk = "";
    private long thaisanPhi;
    private String tncnChk = "";
    private float tncnPhi;
    private String tncnSotienbh = "";
    private String tncnSotienbhTemp = "";
    private long tongPhiBH;
    private long tuoi;
    private String serial = "";
    private String insuranceTarget = "";
    private long loading;
    private long personOrder;
    private String checkReuse = "";
    private String oldPolicyNumber = "";
    private boolean canhBao;
    private boolean collapse;
    private boolean laNYCBH;
    private String hienThiMessageBaoLoiTuoiNDBH = "";
    private String duplicatePassport = "";
    private String insuredName = "";
    private String idPasswport = "";
    private String relationship = "";
    private String loiQuyenLoiChinhKhiNdBhDuoi1Tuoi = "";
    private String loiQuyenLoiChinhKhiNdBhHon1Tuoi = "";
    private QuocTich quocTich;
    private String sex = "";
    private String loiCmndNguoiThuHuong = "";
    private String loiQuanHeNguoiThuHuong = "";
    private String loiTenNguoiThuHuong = "";
}
