package com.lendbiz.p2p.api.request;

import com.lendbiz.p2p.api.request.baovietEntity.AddressDistrictData;
import com.lendbiz.p2p.api.request.baovietEntity.InvoiceInfo;
import com.lendbiz.p2p.api.request.baovietEntity.ListBvgAddBaseVM;
import com.lendbiz.p2p.api.request.baovietEntity.ReceiverUser;
import com.lendbiz.p2p.api.request.baovietEntity.SaleToEmp;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class CreatePolicyPartnerRequest {
    private String agencyConfirmContent;
    private String agencyId;
    private String agencyName;
    private String agencyP1Id;
    private String agencyP1Name;
    private String agencyP2Id;
    private String agencyP2Name;
    private String agencyP3Id;
    private String agencyP3Name;
    private String agencyP4Id;
    private String agencyP4Name;
    private String agencyP5Id;
    private String agencyP5Name;
    private String agencyP6Id;
    private String agencyP6Name;
    private String agencyTextfield1;
    private String agencyTextfield10;
    private String agencyTextfield2;
    private String agencyTextfield3;
    private String agencyTextfield4;
    private String agencyTextfield5;
    private String agencyTextfield6;
    private String agencyTextfield7;
    private String agencyTextfield8;
    private String agencyTextfield9;
    private String agentId;
    private String agentName;
    private String agreeAll;
    private String agreementId;
    private AttachFile[] attachFiles;
    private double changePremium;
    private String checkBvCare;
    private String checkDepartment;
    private String checkOTP;
    private String checkTtskNdbh;
    private String confirmContent;
    private int confirmMethod;
    private String contactAddress;
    private String contactCategoryType;
    private String contactCif;
    private String contactCode;
    private String contactDob;
    private String contactEmail;
    private String contactIdNumber;
    private String contactName;
    private String contactPhone;
    private String conversationContent;
    private String copyFrom;
    private String dateOfCredit;
    private String dateOfPayment;
    private String defaultPolicyNumberBvcare;
    private String departmentId;
    private String departmentName;
    private String dueDateInput;
    private String emailCanBoNganHang;
    private String emailNhanVienGT;
    private String endDateOld;
    private String fullnameDaiLy;
    private String fullnameDisplay;
    private AttachFile[] gcnFiles;
    // private String giftCodeAgency;
    // private int giftCodeAgencyDiscount;
    private int guaranteeCard;
    private AttachFile[] gycFiles;
    private String gycbhId;
    private String gycbhNumber;
    private Boolean hasGks;
    private Boolean hasNguoinhantien;
    private Boolean hasNguoithuhuong;
    private Boolean hasTThoadonGTG;
    private String idNumberNguoiTh1;
    private String idNumberNguoiTh2;
    private AttachFile[] imgGycbhDgrr;
    private String insuranceTarget;
    private InvoiceInfo invoiceInfo;
    private Boolean isFromBVcare;
    private Boolean isShowDgrr;
    private String kenhPhanPhoi;
    private int language;
    private String lineId;
    private ListBvgAddBaseVM[] listBvgAddBaseVM;
    private ListBvgAddBaseVM[] listBvgAddBaseVMAll;
    private String maCanBoNganHang;
    private String maDaiLy;
    private String maNhanVien;
    private double netPremium;
    private String nguoiThuHuong1;
    private String nguoiThuHuong2;
    private String nguoinhanCmnd;
    private String nguoinhanName;
    private String nguoinhanQuanhe;
    private String nguointDiachi;
    private String nguointDienthoai;
    private String nguointEmail;
    private String nguointNgaysinh;
    private String nguoiycAddress;
    private String nguoiycCmnd;
    private String nguoiycEmail;
    private String nguoiycName;
    private String nguoiycNgaysinh;
    private String nguoiycPhone;
    private String note;
    private String oldGycbhNumber;
    private String oldPolicyNumber;
    private String paymentGateway;
    private String paymentMethod;
    private String paymentTransactionId;
    private double phiKhuyenMai;
    private String phongGiaoDich;
    private String policyBvCare;
    private String policyNumber;
    private String promoCode;
    private String promoDES;
    private double promoDiscount;
    private double promoPercent;
    private double promoValue;
    private double promotionPercentage;
    private String promotionalCode;
    private double promotionalDiscountFee;
    private String q1;
    private String q1Question;
    private String q1QuestionDesc;
    private String q1QuestionId;
    private String q1QuestionNote;
    private String q2;
    private String q2Question;
    private String q2QuestionDesc;
    private String q2QuestionId;
    private String q2QuestionNote;
    private String q3;
    private String q3Question;
    private String q3QuestionDesc;
    private String q3QuestionId;
    private String q3QuestionNote;
    private String q4;
    private String q4Question;
    private String q4QuestionDesc;
    private String q4QuestionId;
    private String q4QuestionNote;
    private String q5;
    private String q5Question;
    private String q5QuestionDesc;
    private String q5QuestionId;
    private String q5QuestionNote;
    private String q6;
    private String q6Question;
    private String q6QuestionDesc;
    private String q6QuestionId;
    private String q6QuestionNote;
    private String receiveMethod;
    private ReceiverUser receiverUser;
    private String riskAssessmentContent;
    private String riskAssessmentDescription;
    private String riskAssessmentStatus;
    private SaleToEmp saleToEmp;
    private String showGiamDinh;
    private String skipRiskAssessment;
    private String soHDBaoDam;
    private String statusPolicy;
    private double tangGiamKhac;
    private String tenCanBoNganHang;
    private String tenNhanVienGT;
    private String thoihanbhDen;
    private String thoihanbhTu;
    private double totalPremium;
    private double totalPremiumDGRR;
    private String ttskCheck;
    private String urlPolicy;
    private String urnCanBo;
    private String urnThamChieu;
    private String userAgent;
}
